version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    restart: always
    networks:
      - traefik_proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=leresolver
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=3001

########################### NETWORKS
networks:
  traefik_proxy:
    external: true

