networks:
  traefik_proxy:
    external: true

services:
  uptime-kuma:
    networks:
      - traefik_proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.entrypoints=webs
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.tls.certresolver=leresolver
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=3001